# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Breslow risk-set quantities for Cox sufficient statistics
#'
#' @param X Numeric matrix.
#' @param eta Linear predictor.
#' @param time Survival times.
#' @param status Event indicators (0/1).
#' @param n_threads Number of OpenMP threads for the per-column scans.
#' @return A list with `a` (cumulative hazard weights), `M` (martingale
#'   residuals), `B` (risk-set means of `X` at each event time), `dev`
#'   (events per event time), and `d` (number of events). The Cox information
#'   is `crossprod(X, X * a) - crossprod(B, B * dev)` and the score is
#'   `crossprod(X, M)`.
#' @export
cox_riskset <- function(X, eta, time, status, n_threads = 1L) {
    .Call(`_SuSiE4I_cox_riskset`, X, eta, time, status, n_threads)
}

blockwise_crossprod_cpp <- function(X, n_threads = 4L, block_size = 10000L) {
    .Call(`_SuSiE4I_blockwise_crossprod_cpp`, X, n_threads, block_size)
}

blockwise_crossprod2_cpp <- function(X, Z, n_threads = 4L, block_size = 10000L) {
    .Call(`_SuSiE4I_blockwise_crossprod2_cpp`, X, Z, n_threads, block_size)
}

large_scale_cpp <- function(X, center = TRUE, scale = TRUE, n_threads = 4L) {
    .Call(`_SuSiE4I_large_scale_cpp`, X, center, scale, n_threads)
}

weighted_crossprod_cpp <- function(X, w, M, block_size = 10000L, n_threads = 1L, use_omp = FALSE) {
    .Call(`_SuSiE4I_weighted_crossprod_cpp`, X, w, M, block_size, n_threads, use_omp)
}

